# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ljw_CJXP7yyfKhYe60uDNs4Ykx3wZlly
"""

import streamlit as st
import gdown
from tensorflow.keras.models import load_model
import os
import numpy as np

st.title("AE + GAN Fault Detection")

# -----------------------------
# Download & Load models
# -----------------------------
@st.cache_resource
def load_models():

    # AE model (CLEAN H5)
    if not os.path.exists("ae_model_clean.h5"):
        with st.spinner("Downloading AE model..."):
            gdown.download(
                "https://drive.google.com/uc?id=1mqpemCBWZpCTuh6T0pN3Yr-UoHLPTWtu",
                "ae_model_clean.h5",
                quiet=False
            )

    # GAN model (CLEAN H5)
    if not os.path.exists("gan_generator_clean.h5"):
        with st.spinner("Downloading GAN model..."):
            gdown.download(
                "https://drive.google.com/uc?id=1PcEL3eDUnsR5FMQiqDNfI5jT9X1CsD9F",
                "gan_generator_clean.h5",
                quiet=False
            )

    # Debug info
    if os.path.exists("ae_model_clean.h5"):
        st.write("AE model size (MB):", round(os.path.getsize("ae_model_clean.h5") / (1024*1024), 2))

    # Load models (IMPORTANT FIX)
    ae = load_model("ae_model_clean.h5", compile=False)
    gen = load_model("gan_generator_clean.h5", compile=False)

    return ae, gen


# -----------------------------
# Load models safely
# -----------------------------
try:
    ae, gen = load_models()
    st.success("Models loaded successfully")

except Exception as e:
    st.error(f"Error loading models: {e}")
    st.stop()


# -----------------------------
# GAN Demo
# -----------------------------
st.subheader("Generate Fault Pattern (GAN)")

if st.button("Generate Sample"):
    noise = np.random.normal(0, 1, (1, 64))
    fake = gen.predict(noise)

    st.image(fake[0], clamp=True, caption="Generated Spectrogram")

